### ISSUE TITLE
Unable to commit via tower

### ISSUE THREAD

**Issue by ZenabKhan** [umayr/abracadabra#1]
While committing via terminal it works fine and shows error after linting but I get error when I commit via tower. Following is the error:

```
running lint...failed!
env: node: No such file or directory
```

**Comment by umayr** [comment]
GUI apps on OSX doesn't load the stuff in `.bashrc/.bash_profile`, which means they won't have user specified $PATH additions like `/usr/local/bin`, which is where the node binary is. 

To get this working, you'd have to start the GUI app from your terminal. I'll add this information in the FAQ section.
